---
title: "253_project"
author: "Jinghan"
date: "3/26/2021"
output: html_document
---

```{r}
library(ggplot2)  
library(dplyr)   
library(caret) 
library(ISLR)
library(splines)
library(gam)
library(stringr)
library(leaps)
```

```{r}
#airbnb_kaggle <- read.csv("//Users/zhou/Desktop/253/data/NYC_airbnb_kaggle.csv")
#neighbourhood <- read.csv("//Users/zhou/Desktop/253/data/NYC_nbhd_kaggle.csv")
```
```{r}
airbnb_kaggle <- read.csv("/Users/apple/Downloads/NYC_airbnb_kaggle.csv")
neighbourhood <- read.csv("/Users/apple/Downloads/NYC_nbhd_kaggle.csv")
```

```{r}
set.seed(253)
airbnb <- airbnb_kaggle %>%
  left_join(neighbourhood, c("neighbourhood_cleansed" = "neighbourhood")) %>%
  filter (price < 1000) %>%
  sample_n(5000) %>% 
  select(-id, -host_response_time) %>%
  mutate(host_response_rate = as.numeric(str_remove_all(host_response_rate, "%"))) %>%
  mutate(host_is_superhost = as.logical(toupper(host_is_superhost))) %>%
  mutate(host_has_profile_pic = as.logical(toupper(host_has_profile_pic))) %>%
  mutate(is_location_exact = as.logical(toupper(is_location_exact))) %>%
  mutate(instant_bookable = as.logical(toupper(instant_bookable))) %>%
  mutate(is_business_travel_ready = as.logical(toupper(is_business_travel_ready))) %>%
  mutate(require_guest_profile_picture = as.logical(toupper(require_guest_profile_picture))) %>%
  dplyr::na_if("N/A")
```

```{r}
head(airbnb)
```
```{r}
abnb <- airbnb %>% 
  select(-latitude, -longitude, -amenities)
#write.csv(abnb,"//Users/zhou/Desktop/253/data/abnb.csv", row.names = FALSE)
```


```{r}
#abnb <- read.csv("//Users/zhou/Desktop/253/data/abnb.csv")
```

```{r}
head(abnb)
```

Backward selection:

```{r}
ls_mod  <- lm(price~
                   property_type+
                   room_type+
                   accommodates+
                   beds+
                   guests_included+
                   minimum_nights+
                   availability_30+
                   bathrooms+
                   bedrooms+
                   review_scores_rating+
                   is_business_travel_ready+
                   cancellation_policy+
                   require_guest_profile_picture+
                   reviews_per_month+
                   neighbourhood_group, data = abnb)
summary(ls_mod )

```

```{r}
set.seed(253)
ls_mod <- train(
  price~
                   room_type+
                   accommodates+
                   beds+
                   guests_included+
                   minimum_nights+
                   availability_30+
                   bathrooms+
                   bedrooms+
                   review_scores_rating+
                   is_business_travel_ready+
                   require_guest_profile_picture+
                   reviews_per_month+
                   neighbourhood_group,
    data = abnb,
    method = "lm",
    trControl = trainControl(method = "cv", number = 10),
    na.action = na.omit
)

ls_mod$results
```


```{r}
set.seed(23)

back_step_mod <- train(
  price~
                   room_type+
                   accommodates+
                   beds+
                   guests_included+
                   minimum_nights+
                   availability_30+
                   bathrooms+
                   bedrooms+
                   review_scores_rating+
                   is_business_travel_ready+
                   require_guest_profile_picture+
                   reviews_per_month+
                   neighbourhood_group,
    data = abnb,
    method = "leapBackward",
    tuneGrid = data.frame(nvmax = 1:13),
    trControl = trainControl(method = "cv", number = 10),
    metric = "MAE",
    na.action = na.omit
)
summary(back_step_mod)
```



```{r}
plot(back_step_mod)
back_step_mod$results
back_step_mod$results %>% arrange(MAE)
```

```{r}
back_step_mod$bestTune
coef(back_step_mod$finalModel, id = back_step_mod$bestTune$nvmax)
coef(back_step_mod$finalModel, id = 12)
```



```{r}
set.seed(253)
lasso_mod1 <- train(
    price~
                   room_type+
                   accommodates+
                   beds+
                   guests_included+
                   minimum_nights+
                   availability_30+
                   bathrooms+
                   bedrooms+
                   review_scores_rating+
                   is_business_travel_ready+
                   require_guest_profile_picture+
                   reviews_per_month+
                   neighbourhood_group,
    data = abnb,
    method = "glmnet",
    trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
    tuneGrid = data.frame(alpha = 1, lambda = seq(0, 10, length.out = 100)),
    metric = "MAE",
    na.action = na.omit
)
lasso_mod1$results
```

```{r}
plot(lasso_mod1$finalModel, xvar = "lambda", label = TRUE, col = rainbow(20))
rownames(lasso_mod1$finalModel$beta)
rownames(lasso_mod1$finalModel$beta)[c(2,4)]
```

```{r}
plot(lasso_mod1$finalModel, xvar = "lambda", label = TRUE, col = rainbow(20), ylim = c(-0.5,1))
```

```{r}
plot(lasso_mod1)
```






